import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Homepage</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
        <li>
          <Link to="/project">Project</Link>
        </li>
        <li>
          <Link to="/projectdetailvone">ProjectDetailvOne</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/loginpage">Loginpage</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/master">Master</Link>
        </li>
        <li>
          <Link to="/submittedforms">SubmittedForms</Link>
        </li>
        <li>
          <Link to="/homepageone">HomePageOne</Link>
        </li>
        <li>
          <Link to="/aboutone">AboutOne</Link>
        </li>
        <li>
          <Link to="/contactus">Contactus</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
